### ISSUE TITLE
Fetch and propogate stderr before dying on exception

### ISSUE THREAD

**Issue by ip1981** [zalora/replicator#17]
*Was: hPutBuf: resource vanished (Broken pipe) on import*

```
00:27:34 Importing "/shop/db-slave-db-master-live-tw-zalora-net/replicator-db-master-live-tw-zalora-net.mysql.gz" ... 40%
replicator: fd:12: hPutBuf: resource vanished (Broken pipe)
```

**Comment by ip1981** [comment]
Related to #2

**Comment by ip1981** [comment]
`mysql` terminates due to connection closed by `mysqld`. The reason is `net_read_timeout`. It shuld be large enough.

**Comment by proger** [comment]
I suppose a nicer error message wouldn't hurt

**Comment by ip1981** [comment]
That's mysql bug/feature :-)

**Comment by proger** [comment]
Right, i mean, it's going to be confusing if replicator doesn't warn about that properly :)

**Comment by ip1981** [comment]
https://dev.mysql.com/doc/refman/5.5/en/communication-errors.html

**Comment by proger** [comment]
I'm not sure how this link in this issue is going to help the user who encounter the problem for the first time

**Comment by ip1981** [comment]
This is for me :-P

**Comment by proger** [comment]
woot

though for our cases i can't see anything possible but "A problem with the thread library that causes interrupts on reads"  for now

**Comment by ip1981** [comment]
Consider https://hackage.haskell.org/package/pipes-cliff
